const $=id=>document.getElementById(id);
const record=$('record'),stop=$('stop'),recStatus=$('recStatus'),workflowName=$('workflowName'),save=$('save'),workflows=$('workflows');
const q=$('q'),find=$('find'),results=$('results'),exact=$('exact'),limit=$('limit'),delay=$('delay'),runBulk=$('runBulk'),stopBulk=$('stopBulk'),bulkSummary=$('bulkSummary'),bulkStatus=$('bulkStatus');
let tab=null,recorded=[],matches=[];
const keyForTab=id=>`recording:${id}`;
async function active(){[tab]=await chrome.tabs.query({active:true,currentWindow:true});return tab;}
async function sitePermission(){const u=new URL(tab.url);const origin=`${u.protocol}//${u.host}/*`;if(await chrome.permissions.contains({origins:[origin]}))return true;return chrome.permissions.request({origins:[origin]});}
async function ensureScript(){await active();if(!/^https?:/.test(tab.url))throw new Error('Richmack cannot automate this page.');try{await chrome.tabs.sendMessage(tab.id,{type:'PING'});}catch{await chrome.scripting.executeScript({target:{tabId:tab.id},files:['content.js']});}}
async function refreshRecording(){if(!tab)await active();const k=keyForTab(tab.id),o=await chrome.storage.session.get(k),s=o[k]||{active:false,steps:[]};recorded=s.steps||[];record.disabled=!!s.active;stop.disabled=!s.active;save.disabled=!recorded.length;recStatus.textContent=s.active?`Recording · ${recorded.length} step${recorded.length===1?'':'s'}`:`${recorded.length} recorded step${recorded.length===1?'':'s'}`;}
async function renderWorkflows(){const o=await chrome.storage.local.get('workflows'),arr=o.workflows||[];workflows.replaceChildren();if(!arr.length){workflows.textContent='No saved workflows yet.';workflows.className='muted';return;}workflows.className='';for(const wf of arr){const box=document.createElement('div');box.className='workflow';const title=document.createElement('div');title.innerHTML=`<b>${esc(wf.name)}</b><small>${wf.steps.length} steps</small>`;const run=document.createElement('button');run.textContent='Run';run.onclick=async()=>{try{await ensureScript();recStatus.textContent=`Running “${wf.name}”…`;const r=await chrome.tabs.sendMessage(tab.id,{type:'RM_RUN_WORKFLOW',steps:wf.steps});if(r?.stopped)recStatus.textContent=`Stopped safely: ${r.reason}`;else if(r?.ok)recStatus.textContent='Workflow finished.';else recStatus.textContent=`Workflow failed: ${r?.error||'unknown error'}`;}catch(e){recStatus.textContent=e.message;}};const del=document.createElement('button');del.textContent='×';del.className='mini';del.onclick=async()=>{const n=arr.filter(x=>x.id!==wf.id);await chrome.storage.local.set({workflows:n});renderWorkflows();};const actions=document.createElement('div');actions.className='actions';actions.append(run,del);box.append(title,actions);workflows.append(box);}}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
record.onclick=async()=>{try{if(!(await sitePermission())){recStatus.textContent='Site permission was not granted.';return;}await ensureScript();const k=keyForTab(tab.id);await chrome.storage.session.set({[k]:{active:true,steps:[],origin:new URL(tab.url).origin,started:Date.now()}});await chrome.tabs.sendMessage(tab.id,{type:'RM_RECORD_START'});recorded=[];refreshRecording();window.close();}catch(e){recStatus.textContent=e.message;}};
stop.onclick=async()=>{await ensureScript();await chrome.tabs.sendMessage(tab.id,{type:'RM_RECORD_STOP'}).catch(()=>{});const k=keyForTab(tab.id),o=await chrome.storage.session.get(k),s=o[k]||{steps:[]};s.active=false;await chrome.storage.session.set({[k]:s});refreshRecording();};
save.onclick=async()=>{await refreshRecording();if(!recorded.length)return;const name=workflowName.value.trim()||`Workflow ${new Date().toLocaleString()}`;const o=await chrome.storage.local.get('workflows'),arr=o.workflows||[];arr.unshift({id:crypto.randomUUID(),name,origin:tab?new URL(tab.url).origin:'',steps:recorded,created:Date.now()});await chrome.storage.local.set({workflows:arr.slice(0,50)});workflowName.value='';recStatus.textContent=`Saved “${name}”`;renderWorkflows();};
function renderMatches(){results.replaceChildren();for(const m of matches.slice(0,30)){const d=document.createElement('div');d.className='match';d.innerHTML=`<b>${esc(m.text||'(unnamed control)')}</b><span>${esc(m.context||m.selector||'')}</span>`;results.append(d);}bulkSummary.textContent=`Found ${matches.length} matching visible control${matches.length===1?'':'s'}. Sequence re-checks the page after each click.`;runBulk.disabled=!matches.length;}
find.onclick=async()=>{try{await ensureScript();bulkStatus.textContent='';const r=await chrome.tabs.sendMessage(tab.id,{type:'RM_FIND',query:q.value.trim(),exact:exact.checked});matches=r.matches||[];renderMatches();}catch(e){results.textContent=e.message;runBulk.disabled=true;}};
runBulk.onclick=async()=>{const query=q.value.trim();if(!query||!matches.length)return;const max=Math.max(1,Math.min(Number(limit.value)||10,25)),ms=Math.max(1000,Math.min(Number(delay.value)||2500,10000));if(!confirm(`Run “${query}” on up to ${max} matching controls?\n\nRichmack will wait ${ms} ms between clicks and stop if no matching control remains.`))return;try{await ensureScript();runBulk.disabled=true;stopBulk.disabled=false;bulkStatus.textContent=`Running up to ${max} clicks…`;const r=await chrome.tabs.sendMessage(tab.id,{type:'RM_BULK_RUN',query,limit:max,delay:ms,exact:exact.checked});bulkStatus.textContent=`Clicked ${r.clicked||0}. ${r.stopped?'Stopped.':`Remaining matches: ${r.remaining||0}.`}`;stopBulk.disabled=true;find.click();}catch(e){bulkStatus.textContent=e.message;stopBulk.disabled=true;runBulk.disabled=false;}};
stopBulk.onclick=async()=>{try{await ensureScript();await chrome.tabs.sendMessage(tab.id,{type:'RM_BULK_STOP'});bulkStatus.textContent='Stopping after current click…';}catch(e){bulkStatus.textContent=e.message;}};
q.addEventListener('keydown',e=>{if(e.key==='Enter')find.click();});
(async()=>{await active();await refreshRecording();await renderWorkflows();})();
