(()=>{if(globalThis.__RM_CORE_V051__)return;globalThis.__RM_CORE_V051__=true;let enabled=false,gPending=false,hintLayer=null,hints=[],buffer='';
chrome.storage.local.get('richmackMode').then(x=>enabled=!!x.richmackMode);chrome.storage.onChanged.addListener(c=>{if(c.richmackMode)enabled=!!c.richmackMode.newValue;});chrome.runtime.onMessage.addListener((m,s,send)=>{if(m?.type==='RM_MODE'){enabled=!!m.enabled;toast(`RICHMACK MODE ${enabled?'ON':'OFF'}`);send({ok:true});}return true;});
const editable=e=>e.target?.matches?.('input,textarea,select,[contenteditable=true]');const alphabet='asdfghjklqwertyuiopzxcvbnm';
function hintCodes(count){let width=1,capacity=alphabet.length;while(count>capacity){width++;capacity*=alphabet.length;}return Array.from({length:count},(_,i)=>{let n=i,out='';for(let p=0;p<width;p++){out=alphabet[n%alphabet.length]+out;n=Math.floor(n/alphabet.length);}return out;});}
function toast(t){document.getElementById('rm-core-toast')?.remove();const x=document.createElement('div');x.id='rm-core-toast';x.textContent=t;Object.assign(x.style,{position:'fixed',right:'16px',bottom:'16px',zIndex:2147483647,background:'#07111c',color:'#8ee8ff',border:'1px solid #286fa0',padding:'7px 10px',borderRadius:'7px',font:'600 11px system-ui'});document.documentElement.appendChild(x);setTimeout(()=>x.remove(),1000);}
function clearHints(){hintLayer?.remove();hintLayer=null;hints=[];buffer='';}
function activateHint(el){if(!el||!el.isConnected)return clearHints();el.focus?.({preventScroll:true});const tag=el.tagName?.toLowerCase();if(tag==='a'&&el.href){el.click();}else{el.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,cancelable:true,pointerType:'mouse'}));el.dispatchEvent(new MouseEvent('mousedown',{bubbles:true,cancelable:true,view:window}));el.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,cancelable:true,pointerType:'mouse'}));el.dispatchEvent(new MouseEvent('mouseup',{bubbles:true,cancelable:true,view:window}));el.click();}clearHints();}
function showHints(){clearHints();hints=[...document.querySelectorAll('a[href],button,input[type=button],input[type=submit],[role=button]')].filter(el=>{const r=el.getBoundingClientRect(),cs=getComputedStyle(el);return r.width>3&&r.height>3&&r.bottom>0&&r.top<innerHeight&&r.right>0&&r.left<innerWidth&&cs.visibility!=='hidden'&&cs.display!=='none'&&!el.disabled;}).slice(0,120);const codes=hintCodes(hints.length);hintLayer=document.createElement('div');Object.assign(hintLayer.style,{position:'fixed',inset:0,zIndex:2147483647,pointerEvents:'none'});hints=hints.map((el,i)=>({el,code:codes[i]}));hints.forEach(({el,code})=>{const r=el.getBoundingClientRect(),b=document.createElement('span');b.textContent=code;b.dataset.rm=code;Object.assign(b.style,{position:'fixed',left:`${Math.max(0,r.left)}px`,top:`${Math.max(0,r.top)}px`,background:'#07111c',color:'#75dcff',border:'1px solid #2d86b8',padding:'2px 4px',borderRadius:'4px',font:'700 10px monospace',boxShadow:'0 1px 3px #0008'});hintLayer.appendChild(b);});document.documentElement.appendChild(hintLayer);}
function hintKey(k){buffer+=k;const candidates=hints.filter(h=>h.code.startsWith(buffer));hintLayer.querySelectorAll('span').forEach(s=>s.style.display=s.dataset.rm.startsWith(buffer)?'':'none');if(!candidates.length){buffer='';hintLayer.querySelectorAll('span').forEach(s=>s.style.display='');toast('NO HINT');return;}const exact=candidates.find(h=>h.code===buffer);if(exact)activateHint(exact.el);}
function command(){document.getElementById('rm-command')?.remove();const wrap=document.createElement('div');wrap.id='rm-command';Object.assign(wrap.style,{position:'fixed',left:'50%',top:'15%',transform:'translateX(-50%)',zIndex:2147483647,width:'min(620px,80vw)',background:'#07111c',border:'1px solid #2c7dac',borderRadius:'10px',padding:'8px',boxShadow:'0 16px 50px #000a'});const i=document.createElement('input');i.placeholder=': open github.com · back · forward · close · undo';Object.assign(i.style,{width:'100%',boxSizing:'border-box',background:'#0a1825',border:'1px solid #1d4e70',color:'#d8f5ff',padding:'11px',borderRadius:'7px',font:'14px system-ui',outline:'none'});wrap.appendChild(i);document.documentElement.appendChild(wrap);i.focus();const done=()=>wrap.remove();i.addEventListener('keydown',e=>{if(e.key==='Escape')done();if(e.key==='Enter'){runCommand(i.value);done();}});}
function runCommand(raw){const x=raw.trim().replace(/^:/,'');if(x==='back')history.back();else if(x==='forward')history.forward();else if(x==='close')chrome.runtime.sendMessage({type:'RM_CLOSE'});else if(x==='undo')chrome.runtime.sendMessage({type:'RM_UNDO'});else if(x.startsWith('open ')){let u=x.slice(5).trim();if(!/^https?:/i.test(u))u='https://'+u;chrome.runtime.sendMessage({type:'RM_OPEN',url:u});}else if(x.startsWith('workspace '))chrome.runtime.sendMessage({type:'RM_WORKSPACE',workspace:x.slice(10).trim()});}
document.addEventListener('keydown',e=>{if(!enabled||editable(e))return;if(hintLayer){if(e.key==='Escape'){clearHints();return;}if(/^[a-z]$/.test(e.key)){e.preventDefault();hintKey(e.key);}return;}if(gPending){gPending=false;if(e.key==='g'){e.preventDefault();scrollTo({top:0,behavior:'smooth'});return;}}switch(e.key){case'j':e.preventDefault();scrollBy({top:Math.max(120,innerHeight*.45),behavior:'smooth'});break;case'k':e.preventDefault();scrollBy({top:-Math.max(120,innerHeight*.45),behavior:'smooth'});break;case'h':e.preventDefault();history.back();break;case'l':e.preventDefault();history.forward();break;case'G':e.preventDefault();scrollTo({top:document.documentElement.scrollHeight,behavior:'smooth'});break;case'g':gPending=true;setTimeout(()=>gPending=false,500);break;case'f':e.preventDefault();showHints();break;case'J':e.preventDefault();chrome.runtime.sendMessage({type:'RM_NEXT',direction:-1});break;case'K':e.preventDefault();chrome.runtime.sendMessage({type:'RM_NEXT',direction:1});break;case'd':e.preventDefault();chrome.runtime.sendMessage({type:'RM_CLOSE'});break;case'u':e.preventDefault();chrome.runtime.sendMessage({type:'RM_UNDO'});break;case':':e.preventDefault();command();break;}} ,true);
})();
