const $=id=>document.getElementById(id);let tab=null,scan=null;const tabs=[...document.querySelectorAll('nav button')];
async function activeTab(){const[t]=await chrome.tabs.query({active:true,currentWindow:true});return t||null}async function send(msg){tab=await activeTab();if(!tab?.id)throw new Error('No tab');await chrome.scripting.executeScript({target:{tabId:tab.id},files:['content.js']});return chrome.tabs.sendMessage(tab.id,msg)}
tabs.forEach(b=>b.onclick=()=>{tabs.forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view));if(b.dataset.view==='workspace')renderWorkspace();if(b.dataset.view==='automate')loadPicked()});
async function loadMode(){const{richmackMode=false}=await chrome.storage.local.get('richmackMode');$('mode').textContent=richmackMode?'MODE ON':'MODE OFF'}$('mode').onclick=async()=>{const{richmackMode=false}=await chrome.storage.local.get('richmackMode');await chrome.runtime.sendMessage({type:'RM_SET_MODE_BG',enabled:!richmackMode});loadMode()};
async function renderWorkspace(){tab=await activeTab();const{workspaces=[],activeWorkspace='Development',tabWorkspace={},smartBookmarks=[]}=await chrome.storage.local.get(['workspaces','activeWorkspace','tabWorkspace','smartBookmarks']);$('workspaces').replaceChildren(...workspaces.map(w=>{const b=document.createElement('button');b.className=w.id===activeWorkspace?'active':'';b.textContent=w.name;b.onclick=async()=>{await chrome.runtime.sendMessage({type:'RM_SWITCH_WORKSPACE',workspace:w.id});renderWorkspace()};return b}));const q=$('filter').value.toLowerCase();$('bookmarks').replaceChildren(...smartBookmarks.filter(b=>!q||`${b.title} ${b.url}`.toLowerCase().includes(q)).slice(0,30).map(b=>{const d=document.createElement('div');d.className='item';d.innerHTML=`<strong>${b.title}</strong><small>${b.workspace} · ${b.url}</small>`;d.onclick=()=>chrome.tabs.create({url:b.url});return d}));$('assign').dataset.workspace=activeWorkspace;$('assign').title=tabWorkspace[String(tab?.id)]||''}
$('filter').oninput=renderWorkspace;$('assign').onclick=async()=>{tab=await activeTab();const{activeWorkspace='Development'}=await chrome.storage.local.get('activeWorkspace');await chrome.runtime.sendMessage({type:'RM_ASSIGN_WORKSPACE',tabId:tab.id,workspace:activeWorkspace});renderWorkspace()};$('bookmark').onclick=async()=>{tab=await activeTab();const d=await chrome.storage.local.get(['smartBookmarks','activeWorkspace']);const list=d.smartBookmarks||[];if(!list.some(x=>x.url===tab.url))list.unshift({id:crypto.randomUUID(),url:tab.url,title:tab.title||tab.url,workspace:d.activeWorkspace||'Development',tags:[],unread:true,createdAt:Date.now()});await chrome.storage.local.set({smartBookmarks:list});renderWorkspace()};
function renderScan(s){scan=s;const vals=[['Links',s.links?.length||0],['Images',s.images?.length||0],['Emails',s.emails?.length||0],['PDFs',s.pdfs?.length||0],['Files',s.files?.length||0],['Text',Math.round((s.text?.length||0)/1000)+'k']];$('stats').innerHTML=vals.map(([k,v])=>`<div class="stat"><strong>${v}</strong><small>${k}</small></div>`).join('');$('output').textContent=[`TITLE: ${s.title||tab?.title||''}`,`URL: ${s.url||tab?.url||''}`,'',...(s.links||[]).slice(0,60)].join('\n')}
function resource(raw){try{const u=new URL(raw);const p=u.pathname.toLowerCase();for(const [type,rx]of[['PDF',/\.pdf$/],['FILE',/\.(epub|txt|md|csv|json|zip)$/]])if(rx.test(p))return{type,url:u.href};}catch{}return null}
$('scan').onclick=async()=>{tab=await activeTab();const r=resource(tab?.url||'');if(r){renderScan({url:tab.url,title:tab.title,links:[tab.url],images:[],emails:[],pdfs:r.type==='PDF'?[tab.url]:[],files:r.type==='FILE'?[tab.url]:[],text:''});return}try{renderScan(await send({type:'RM_EXTRACT'}))}catch(e){$('output').textContent='Scan unavailable on this Chromium-managed page.'}};$('copyLinks').onclick=()=>scan&&navigator.clipboard.writeText((scan.links||[]).join('\n'));$('copyEmails').onclick=()=>scan&&navigator.clipboard.writeText((scan.emails||[]).join('\n'));async function dl(list){for(const u of(list||[]).slice(0,25))await chrome.downloads.download({url:u}).catch(()=>{})}$('images').onclick=()=>scan&&dl(scan.images);$('pdfs').onclick=()=>scan&&dl(scan.pdfs);$('text').onclick=async()=>{if(!scan?.text)return;const u=URL.createObjectURL(new Blob([scan.text],{type:'text/plain'}));await chrome.downloads.download({url:u,filename:'richmack/page-text.txt'});setTimeout(()=>URL.revokeObjectURL(u),3000)};
$('pick').onclick=async()=>{try{await send({type:'RM_START_PICKER'})}catch{} };async function loadPicked(){const{lastPicked=null}=await chrome.storage.local.get('lastPicked');$('picked').hidden=!lastPicked;if(lastPicked){$('selector').textContent=lastPicked.selector;$('pickedText').textContent=lastPicked.text||lastPicked.url||''}}$('run').onclick=async()=>{const{lastPicked}=await chrome.storage.local.get('lastPicked');if(lastPicked)await send({type:'RM_CLICK_SELECTOR',selector:lastPicked.selector})};
chrome.tabs.onActivated.addListener(()=>{scan=null;$('stats').replaceChildren();$('output').textContent='Nothing scanned yet.';tab=null});chrome.tabs.onUpdated.addListener((id,c)=>{if(c.url){scan=null;$('stats').replaceChildren();$('output').textContent='Nothing scanned yet.'}});chrome.storage.onChanged.addListener(()=>{loadMode();loadPicked()});loadMode();renderWorkspace();loadPicked();
